#!/bin/bash

ping -c1 192.168.1.1
	if [ $? -eq 0 ]
	then
	echo OK
	else
	echo NOT OK
	fi



 
ping -c1 192.168.1.1 &> /dev/null
		if [ $? -eq 0 ]
		then
		echo OK
		echo NOT OK
		fi

hosts="192.168.1.1"
ping -c1 $hosts &> /dev/null
		if [ $? -eq 0 ]
		then
		echo $hosts OK
		else
		echo $hosts NOT OK
		fi